default_language_version:
  python: python3.12
default_stages: [commit, push]
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.2
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]